#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:30:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

mkdir -p out_dir
mkdir -p out_data
mkdir -p brainstorm_db

# Run MatLab code local
# matlab -nodisplay -r main
# ./brainstorm3.command /usr/local/MATLAB/MATLAB_Runtime/v98/ main.m

singularity run -e docker://brainlife/brainstorm:3_210303 main.m local
# singularity exec -e -B `pwd`:$HOME docker://brainlife/brainstorm:3_210303 main.m local
